### ISSUE TITLE
Improve the github workflow

### ISSUE THREAD

**Issue by francisrstokes** [francisrstokes/super-expressive#10]
- [ ] Introduce a workflow for running the tests and reporting the coverage
- [ ] Create a PR template with a checklist
  - [ ] Is the change purely for documentation purposes?
    - Please include a summary of changes and an explanation
  - [ ] Does the change introduce new functionality?
    - [ ] Does the code style reasonably match the existing code?
    - [ ] Are the changes tested (using the existing format, as far as is possible?)
    - [ ] Are the changes documented in the readme with a suitable example?
    - [ ] Is the table of contents updated?
    - [ ] Is the `index.d.ts` file updated, using the same description as the readme?
  - [ ] This PR introduces some other kind of change
    - Please explain the change below

**Comment by RoyiAvital** [comment]
Any option to online version with UI?
