### ISSUE TITLE
Why not support plural form?

### ISSUE THREAD

**Issue by kalmanh** [francisrstokes/super-expressive#15]
In addition to

`SuperExpressive().exactly(5).digit`

why not support

`SuperExpressive().exactly(5).digits`

?

**Comment by francisrstokes** [comment]
Hey @kalmanh,

I have thought about this, and it basically comes down to predictability. Let's imagine you use the `.digits` property without `.exactly(x)`. what would you expect the regex to look like?

- `/\d+/`?
- `/\d+?/`?
- `/\d*/`?
- `/\d*+/`?
- `/\d{1,}/`?

Even if you're able to make a decision about how to handle that ambiguity, you then have to deal with the fact that it needs to generate differently depending on what quantifier is specified. That would complicate the mechanism that deals with quantification, increasing the code size and potential for bugs.

I actually don't think it's insurmountable - all of these concerns could be reasonably addressed - but at the moment I personally don't see the benefits outweighing the costs. I'll leave the issue open for other people to provide input.

Thanks for the feedback!

**Comment by kalmanh** [comment]
@francisrstokes - you have a point there, but if one of the main goals of the project is to be as expressive as possible `SuperExpressive().exactly(5).digit` is pretty lame (and not very natural :expressionless: ).

**Comment by francisrstokes** [comment]
I absolutely agree that in a lot of cases like the one you've shown, a pluralisation would read better, and thus be more expressive. But expressiveness is more than just that one point. `digits` highlights a place where ambiguity arises in a potentially unpredictable way - leading to situations where a user *thinks* they're expressing one idea, but actually get something completely different.

**Comment by stanislav-tsaplev** [comment]
> Let's imagine you use the `.digits` property without `.exactly(x)`. what would you expect the regex to look like?

I'd expect an exception :)

**Comment by francisrstokes** [comment]
> I'd expect an exception :)

Personally I would find that to be a really frustrating API; it feels like you're setting a trap for the user to fall into. IMO the API should be designed in a way that, given the right kind of language integration tooling, actually helps *guide* you towards a correct implementation.
