### ISSUE TITLE
Support named capture groups and backreferences

### ISSUE THREAD

**Issue by ShimShamSam** [francisrstokes/super-expressive#2]
First of all, cool concept! Something I would find useful is the ability to use named capture groups.

I think naming a group could be as simple as

`.capture('my_name')`

Backreferences could be one of the following:

`.backreference('my_name')`
`.group('my_name')`
`.captureGroup('my_name')`

Bonus points if you support numeric backreferences, but with naming them being so easy, I don't see too much use:

`.backreference(2)`

**Comment by francisrstokes** [comment]
Hey @ShimShamSam - these are all great features to support. API-wise I think `.namedX(groupName)` will make an easy distinction from unnamed groups. I'll look into adding this when I have some time later this evening.
