### ISSUE TITLE
Prettier formatting

### ISSUE THREAD

**Issue by will-stone** [francisrstokes/super-expressive#24]
Hi. Thanks for this package. I really struggle with regex and I'll certainly be using this in the future.

I've only got as far as your example but I see a potential issue. You are using indentation as a guide, which is great but does not work well in a Prettier world, for example, your example is changed to have no nesting:

```js
const SuperExpressive = require('super-expressive')

const myRegex = SuperExpressive()
  .startOfInput.optional.string('0x')
  .capture.exactly(4)
  .anyOf.range('A', 'F')
  .range('a', 'f')
  .range('0', '9')
  .end()
  .end()
  .endOfInput.toRegex()
```

I'm not quite sure what the answer is here, other than something like this maybe:

```js
const SuperExpressive = require('super-expressive')

const myRegex = SuperExpressive()
  .startOfInput((se) =>
    se.optional
      .string('0x')
      .capture((se) =>
        se.exactly(4).anyOf.range('A', 'F').range('a', 'f').range('0', '9'),
      ),
  )
  .toRegex()
```

or

```js
const se = require('super-expressive')

const myRegex = se()
  .startOfInput(
    se.optional
      .string('0x')
      .capture(
        se.exactly(4).anyOf.range('A', 'F').range('a', 'f').range('0', '9'),
      ),
  )
  .toRegex()
```

But either would be a major shake-up to your API 🤷

**Comment by francisrstokes** [comment]
Hey @will-stone - yeah this is a bit of a shame, and one of the main reasons that, for my own projects, I don't use any kind of autoformatter. I like to be able to structure code in a meaningful way, and that's often lost in catch-all tools like prettier. I'm not against them per se (having a common format in teams can avoid some code review annoyances) - but removing the ability to use the way code is laid out as a communication tool for the sake absolute consistency is a negative.

I think the best thing to do when you have a prettier/eslint project you want to use it in is to just

```javascript
// prettier-ignore
const myRegex = SuperExpressive()
  .startOfInput.optional.string('0x')
  .capture
    .exactly(4).anyOf
      .range('A', 'F')
      .range('a', 'f')
      .range('0', '9')
    .end()
  .end()
  .endOfInput
  .toRegex();
```

Which I think is the best of both worlds. Expressive code layout where you explicitly want it, while keeping the rest of the codebase consistent for easy code review etc.

**Comment by will-stone** [comment]
I suppose everyone likes what they are used to; I couldn't live without Prettier now 😔

`prettier-ignore` is certainly a solution, and one I would choose to avoid writing regex. To be honest, I wasn't ever expecting you to completely rewrite your api for the sake of some indentation, I just thought I'd mention this as I probably won't be the first to have the same thought and some devs may not even now about `prettier-ignore`.

Thanks!
