### ISSUE TITLE
Can't use multiple endOfInput

### ISSUE THREAD

**Issue by sandervspl** [francisrstokes/super-expressive#30]
This is probably a niche case, but it's still something that I need and I can't express with this library (or can't figure out how to).

My case is that I have three groups that are all optional, but it should match at least one of those.

The regex I need is:
`/^(?!$)(?:\d+g)?(?:\s*\d+s)?(?:\s*\d+c)?$/i`

The playground code that I currently have for this is:

```
SuperExpressive()
    .caseInsensitive
    .startOfInput
    .assertNotAhead
        .endOfInput
        // I also tried this
        // .subexpression(SuperExpressive().endOfInput, { ignoreStartAndEnd: false })
    .end()
    .optional.group
    .oneOrMore.digit
    .char('g')
    .end()
    .optional.group
        .zeroOrMore.whitespaceChar
        .oneOrMore.digit
        .char('s')
    .end()
    .optional.group
        .zeroOrMore.whitespaceChar
        .oneOrMore.digit
        .char('c')
    .end()
    .endOfInput
    .toRegex()
```

If there's another way to write this regex it's much appreciated. The `(?!$)` trick is the only answer I could find that works with my case of all optional groups.

**Comment by francisrstokes** [comment]
Hey Sander,

Sorry to leave you hanging for a week - I somehow missed this issue. You're right in that super expressive doesn't current support using `endOfInput` in this way. I'm wondering if you can't express you're problem like this instead:


```javascript
const pattern1 = SuperExpressive()
  .group
    .oneOrMore.digit
    .char('g')
  .end();

const pattern2 = SuperExpressive()
  .group
    .zeroOrMore.whitespaceChar
    .oneOrMore.digit
    .char('s')
  .end();

const pattern3 = SuperExpressive()
  .group
    .zeroOrMore.whitespaceChar
    .oneOrMore.digit
    .char('c')
  .end();

const wholePattern = SuperExpressive()
  .caseInsensitive
  .startOfInput
  .anyOf
    .subexpression(pattern1)
    .subexpression(pattern2)
    .subexpression(pattern3)
  .end()
  .endOfInput
  .toRegex();
```

Which produces the regex:

```
/^(?:(?:\d+g)|(?:\s*\d+s)|(?:\s*\d+c))$/i
```

That ensures one and only of your patterns are matched, and that it's always followed by the end of input. Obviously you don't have to split them into subexpressions - you could inline everything and it should work the same.
