### ISSUE TITLE
some question about `anyof` operator.

### ISSUE THREAD

**Issue by gemmi** [francisrstokes/super-expressive#31]
i want a patter `/xxx|yyy/`, if i use `anyof` operator i get `/(?:xxx|yyy)/`, this is non-capture group, so i can't get real groups:
```js
SuperExpressive()
.anyOf
    .string('xxx')
    .string('yyy')
.end()
.toRegex()
```
get: 
```
> /(?:xxx|yyy)/.exec('xxxx234xxxsdf')
> ["xxx", index: 0, input: "xxxx234xxxsdf", groups: undefined]

> /(xxx|yyy)/.exec('xxxx234xxxsdf')
> (2) ["xxx", "xxx", index: 0, input: "xxxx234xxxsdf", groups: undefined]
```
anyway, i cant get capture-group by adding `capture` operator prefixed:
```js
SuperExpressive()
.capture.anyOf
    .string('xxx')
    .string('yyy')
.end()
.end()
.toRegex()
```
get
```
> /((?:xxx|yyy))/.exec('xxxx234xxxsdf')
> (2) ["xxx", "xxx", index: 0, input: "xxxx234xxxsdf", groups: undefined]
```
is there any other way to get the simple one ？

**Comment by francisrstokes** [comment]
It's true that `anyOf` generates a non-capturing group, but if you use `capture` (or `namedCapture`), you'll still be able to get the group result. So:

```javascript
/(xxx|yyy)/
```

Is functionally equivalent to:

```javascript
/((?:xxx|yyy))/
```

Is there a reason you'd need to generate the exact output `(/xxx|yyy)/`?
