### ISSUE TITLE
Porting for Ruby

### ISSUE THREAD

**Issue by hiy** [francisrstokes/super-expressive#34]
Hi. Thank you for the wonderful library!

I usually write programs using Ruby.
So I made a port for Ruby so that I can use super-expressive in Ruby as well.
If you don't mind, I would like to publish a super-expressive for Ruby.
Is that okay?

**Comment by francisrstokes** [comment]
Hi @hiy,

Sounds awesome - I wouldn't have a problem with that, and would be happy to post a link in the readme as well! Is the code already online? I'd love to see it.

**Comment by hiy** [comment]
@francisrstokes 

Thank you for allowing me to do this!
And it is now available at the following link

https://github.com/hiy/super-expressive-ruby

**Comment by francisrstokes** [comment]
No worries! Thanks for taking time to make a port 😄 [You'll find a link in the readme in the ports section.](https://github.com/francisrstokes/super-expressive#Ports).
