### ISSUE TITLE
Is there a way of compiling regex at build time.

### ISSUE THREAD

**Issue by MattyBalaam** [francisrstokes/super-expressive#36]
I'm one of those people who avoids regex at all times because of it's readability issues, but I love its conciseness.

From the readme is appears that this library is runtime only, but I was wondering if there could be a way of compiling into regex for production to combine the best of both worlds?

**Comment by francisrstokes** [comment]
Someone proposed a babel plugin at some point - that would be a way to do it, but it isn't something that I've worked on.

**Comment by MattyBalaam** [comment]
Maybe it’s time to write my first babel plugin 🤔

**Comment by coolhome** [comment]
I think a typescript compile transformer could also work very nicely.

**Comment by arthurdenner** [comment]
Hey everyone! 👋🏽 

I played a bit with the idea of this issue and created [`super-expressive.macro`](https://github.com/arthurdenner/super-expressive.macro) that allows some expressions to be compiled at build-time.

There are two open-issues regarding variables and subexpressions but I think it's in a good shape for a not-so-advanced usage of `super-expressive`.

I appreciate any feedback, suggestions and PRs and would like to thank @francisrstokes for creating `super-expressive` in the first place!

**Comment by francisrstokes** [comment]
I meant to reply to this a long time ago, but life and children have drastically shrunk my project availability time 😄 This is really cool @arthurdenner, hats off to you!

I think we can consider this issue closed now. @arthurdenner I'd be honored if you made a PR adding a section to the readme  (somewhere around the "ports" section) mentioning the macro and linking off your repo.

**Comment by MattyBalaam** [comment]
I think I left a thumbs up, but thanks again @arthurdenner and @francisrstokes - I'm currently on a team building a new product and will definitely suggest this easy to read solution once we start needing to use Regex.
