### ISSUE TITLE
incomplete *Lazy coverage

### ISSUE THREAD

**Issue by chris-findlay** [francisrstokes/super-expressive#40]
While you have covered all variants of `{,}`, including `*` and `+`, the lazy alternatives are missing for `exactly` and `atLeast`.

**Comment by francisrstokes** [comment]
Hey Chris - indeed, `atLeast` should have a lazy equivalent. For `exactly` I don't think it would make sense, since the regex can't match more anyway (though there could be a `exactlyLazy` that just dispatches to `exactly`, this might cause more confusion than it's worth).

**Comment by chris-findlay** [comment]
True - I guess it is a bit of a trap for when writing REs that `a{4}` === `a{4}?` !== `(?:a{4})?`.
