### ISSUE TITLE
lookBehind API missing from playground

### ISSUE THREAD

**Issue by chris-findlay** [francisrstokes/super-expressive#41]
The docs mention `assertBehind` and `assertNotBenind` but they don't work in the playground.

Also, JS didn't used to support lookBehind, only lookAhead - might be worth documenting when this changed?

**Comment by francisrstokes** [comment]
Hi Chris - Super Expressive Playground is a separate project maintained by @narct, so this issue is probably better suited there: https://github.com/nartc/super-expressive-playground

**Comment by chris-findlay** [comment]
Thoughts on the last bit?  I'm pretty sure that for a while JS only had lookAhead.

**Comment by francisrstokes** [comment]
Indeed it did. I think it's a fair point actually (though I don't have any intention of trying to provides backwards compatibility). I'd happily accept a PR making a note on the related method in the readme

**Comment by chris-findlay** [comment]
Found out when: https://medium.com/@bramus/javascript-whats-new-in-ecmascript-2018-es2018-17ede97f36d5#ca4f

**Comment by chris-findlay** [comment]
And it wasn't just lookBehind added then (c:
