### ISSUE TITLE
Is it possible to make reverse interpreter? (regex -> js)

### ISSUE THREAD

**Issue by hmmhmmhm** [francisrstokes/super-expressive#42]
This project was so good that I suddenly thought of it, is it impossible to make a code that converts the existing regular expression into the code of this project?

**Comment by francisrstokes** [comment]
At this point I think it would be mostly possible, yes - I don't think the project is missing any regex features that would prevent it.

You'd have to parse the regex string (shameless plug: try with [arcsecond](https://github.com/francisrstokes/arcsecond)), then construct a super expressive object from the parse tree - which would be more or less 1-to-1.

Let me know if you end up pursing it - it would be pretty interesting to see!
