### ISSUE TITLE
include replace examples

### ISSUE THREAD

**Issue by uweiner** [francisrstokes/super-expressive#5]
It would be great to demonstrate how to use it in a search and replace scenario, like in:
`str.replace(/(Cap1.+)_(Cap2.+)/, "Capture group 1 is $1, Capture group 2 is $2")`

**Comment by francisrstokes** [comment]
Yeah that's a good idea. The whole example section could do with a bit of expanding.

**Comment by francisrstokes** [comment]
I'm working on improving the capture group functionality at the moment in relation to #2 - so I'll take a look into this when that's in place
