### ISSUE TITLE
Question: How can I exclude a word if it contains something?

### ISSUE THREAD

**Issue by jamesmenera** [francisrstokes/super-expressive#50]
Example: I am trying to grab everything except in the case that it is not an email. So I want to do something like `John L. Weston-Smith` unless `john.l.weston.smith@email.com`? So basically if the `@` symbol is present don't capture

**Comment by francisrstokes** [comment]
Hey James - You need to look at the [`assertNotAhead`](https://github.com/francisrstokes/super-expressive#assertNotAhead) API
