### ISSUE TITLE
Does anythingButString work as intended?

### ISSUE THREAD

**Issue by stanislav-tsaplev** [francisrstokes/super-expressive#58]
.anythingButString(str) is documented like this:
> Matches any string the same length as str, except the characters sequentially defined in str.

`SuperExpressive()
  .anythingButString('aeiou')
  .toRegex();
// ->
/(?:[^a][^e][^i][^o][^u])/`

But what the case it has covered? It's not the case of matching any string not equal to str: it would reject any word having one (or more) of the listed charachers at the corresponding position (as said [here](https://www.oreilly.com/library/view/regular-expressions-cookbook/9781449327453/ch05s04.html)). Is this how it was planned?

**Comment by francisrstokes** [comment]
Yes you're correct. As far as I know, there is no direct way to negatively capture a string like this, other than the method I've implemented. Note that this is different to the O'Reilly link you included, as a negative lookahead does not capture any input.

Now I think about it a little, I guess generating something like

```javascript
SuperExpressive().anythingButString('aeiou').toRegex()

/(?:(?!aeiou].{5})/
```

could work, although there would be some complexity around unicode, with making sure that the correct number of characters were really captured.

**Comment by stanislav-tsaplev** [comment]
By the way, there's no tests for `anythingButString` in `index.tests.js` for now.
